Welcome to the `Python Introduction Workshop`! In this notebook, we will quickly go over basic concepts of Python programming language. We will then learn about several packages that we will use in our workshops, including Numpy and Matplotlib. We will finish this notebook by studying n-balls and observe something interesting together.


<div class="alert alert-block alert-info">

# 1. Python basics 

For this workshop we will be using the Python programming language! Python is an "interpreted" language, which means that there is no need to compile code before we run it! This means we can use programs like Jupyter to create and run code in an "interactive" setting which aids in prototyping and learning of new ideas!

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Python_logo_and_wordmark.svg/2880px-Python_logo_and_wordmark.svg.png" width="400" align="center">

## 1.1 Values & Variables 

Before we beginning, Python has the following common data types built-in by defualt:
- Text type:       
    - `str` - string
- Numeric types:   
    - `int` - integer 
    - `float` - floating point 
    - `complex` - complex number
- Boolean type:
    - `bool` - boolean

Python variables do not need explicit declaration to reserve memory space. The declaration happens automatically when you assign a value to a variable. The equal sign (=) is used to assign values to variables.

In [ ]:
a = 'Python workshop'   # String
b = 10              # Integer
c = 1.23            # Floating point
d = complex(1, 2)   # Complex number
e = True            # Boolean

In python notebooks, you can call a variable to display its value. Try it yourself (change `a` to `b`, `c`, ...) to display the variables defined above.

In [ ]:
a   # Display the value of a variable.

In Python, within a line, everything after a hashtag '`#`' is considered as comments, and they will not be seen and interpreted when running the code. The comments are usually used to ensure readability of your code for you and your code readers (including yourself in the future!). So, it is always a good practice to add comments.

There are more compact ways to print strings with numerical values, where manual casting is not needed. For example, you can use 

- Formatting string literals (also called f-strings for short)
- The string `format()` method

Let's try these methods below.

In [ ]:
name = "Tim"    # A string
age = 21        # An integer
time = 1.2345   # A float

# F-strings
# Formatted String Literals let you include variables within the printed string - need to define type as well
print(f'My name is {name} and I am {age} years old, I\'ve been learning Python for {time:.2f} mins.')

# format()
# similar to f-strings, instead, you put the variables inside .format() at the end of the message.
print('My name is {} and I am {} years old, I\'ve been learning Python for {:.2f} mins.'.format(name, age, time))

### Operators 

Like in other programming languages, arithmatic operators allow us to perform arithmatic:

In [ ]:
a = 2
b = 3

print(a + b)  # Addition
print(a - b)  # Subtraction
print(a * b)  # Multiplication
print(a / b)  # Division
print(a // b) # Integer (or floored) division
print(a % b)  # Modulus
print(a ** b) # Exponent
print(a ^ b)  # NOT EXPONENT (XOR operation)

Assignment operators combine assigning values to variables and athithatic operators:

In [ ]:
a = 10
print(a)
a += 2   # a = a + 2
print(a)
a -= 3   # a = a - 3
print(a)
a *= 10  # a = a*10
print(a)
a /= 20  # a = a/20
print(a)

Comparison operators perform comparisons between variables and return booleans (i.e. True/False):

In [ ]:
a = 2
b = 3

print(a == b) # Equal to
print(a != b) # Not equal to
print(a > b)  # Greater than
print(a < b)  # Less than
print(a >= b) # Greater than or equal to
print(a <= b) # Less than or equal to

Logical operators perform logic operations:

In [ ]:
a = True
b = False
print(a and b)  # Logical and
print(a or b)   # Logical or
print(not a)    # Not operator
print(not b)    # Not operator

### Standard Data Types

The data stored in memory can be of many types. For example, a person's age is stored as a numeric value and his or her address is stored as alphanumeric characters. Python has various standard data types that are used to define the operations possible on them and the storage method for each of them.

Including the 5 data types introduced at the beginning, Python has these common standard data types:

- Number (including `int`, `float` and `complex`)
- String
- List
- Tuple
- Dictionary


Note that the underscore at the end of the variable '`str_`' is to avoid variable name clash with all the pre-defined Python variables or functions. For example '`str`' here is a pre-defined function to turn other variable types to a string as we introduced above.

### Python Lists 

Lists are the most versatile of Python's compound data types. A list contains items separated by commas and enclosed within square brackets (`[]`). To some extent, lists are similar to arrays in C. One of the differences between them is that all the items belonging to a list can be of different data type.

The values stored in a list can be accessed using the slice operator (`[ ]` and `[:]`) with indexes starting at 0 in the beginning of the list and working their way to end -1. The plus (`+`) sign is the list concatenation operator, and the asterisk (`*`) is the repetition operator. For example −

In [ ]:
list_ = [ 'abcd', 786 , 2.23, 'john', 70.2 ]

print(list_)            # Prints complete list
print(list_[0])         # Prints first element of the list
print(list_[1:3])       # Prints elements starting from 1st till 2nd

The `append()` function can be used to append elements to the end of a list, and the `len()` function can be used to get the length of a list (i.e. the number of elements):

In [ ]:
list_.append('Another element') #Append element to end of list
print(list_)
print(len(list_))

### Python Dictionary 

Python's dictionaries are kind of hash-table type. They work like associative arrays or hashes found in Perl and consist of key-value pairs. A dictionary key can be almost any Python type, but are usually numbers or strings. Values, on the other hand, can be any arbitrary Python object.

Dictionaries are enclosed by curly braces (`{ }`) and values can be assigned and accessed using square braces (`[]`). For example −

In [ ]:
dict_ = {}
dict_['one'] = "This is one"
dict_[2]     = "This is two"

tinydict = {'name': 'john','code':6734, 'dept': 'sales'}

print (dict_['one'])       # Prints value for key 'one'
print (dict_[2])           # Prints value for key 2 
print (tinydict)          # Prints complete dictionary
print (tinydict.keys())   # Prints all the keys
print (tinydict.values()) # Prints all the values

Dictionaries have no concept of order among the elements. In addition, if you're not sure about the data type of a variable, you can use the `type()` function to check. See [here](https://www.programiz.com/python-programming/methods/built-in/type) for documentation about `type`.

In [ ]:
var1_unknown = 1.23
var2_unknown = [1, 'string']

print(type(var1_unknown), type(var2_unknown))

## Conditional Statements 

Note the usage of colons and identation. This is analogous to C's curly brackets which defines the scope of a function/conditional statement

In [ ]:
var = 100

if (var==50):
    print('Value of expression is 50')
elif(var==100): # else if statement is written as 'elif' in python.
    print('Value of expression is 100')
else:
    print('Value of expression is neither 50 or 100')

## Time to try

### Write an if statement to check whether this year (2023) is a leap year.

__Note__: If the year is divisible by 4 and not divisible by 100, or if it is divisible by 400, then it is a leap year

<details>
<summary style="color: yellow; font-weight: bold;">Hint</summary>

```python
year = 2023

if year % 4 ==0 and year % 100 != 0:
    # This type of printing is useful. You need to use the print statement, along with "f" before the string. 
    # Use the curly brackets to place in your variables
    print(f"The year {year} is a leap year")
elif year % 400 == 0:
    print(f"The year {year} is a leap year")
else:
    print(f"The year {year} is not a leap year") 
```

</details>

In [ ]:
# Put your code here

## Loops 

A loop statement allows us to execute a statement or group of statements multiple times. Python has two basic loop types: `while` and `for`.

A `while` loop repeats a statement or group of statements while a given condition is `TRUE`. It tests the condition before executing the loop body.

In [ ]:
counter = 0
while counter < 4:
    print(counter)
    counter += 1

A `for` loop iterates over a sequence, such as a `list`, `tuple` or `string`. The same loop as above can be writen in the following ways:

In [ ]:
numbers = [0,1,2,3]
for counter in numbers:
    print(counter)

To create a sequence of numbers quickly, you can use the `range()` function. See this [document](https://www.programiz.com/python-programming/methods/built-in/range) for more details:



In [ ]:
for counter in range(20, 10, -2):
    print(counter)

Want to escape from the loop? Use:

"`break`" - Exit the loop immediately

Want to skip this iteration of loop? Use:

"`continue`" - End this iteration of the loop imediately, but continue with the next iteration


In [ ]:
for counter in range(10):
    if counter-4 < 0:
        continue
        
    print(counter)
    
    if counter == 7:
        break

## Time to try
### Print a downward Pyramid Pattern of Star using loops with the upper length of 9(stars)
__note__: character could be mutiplified with number to repeat characters. e.g. print("8"*5) will give you '88888'.

<details>
<summary style="color: yellow; font-weight: bold;">Hint</summary>

```python
# define the upper length
total_number_of_stars = 9

# init the first layer length
number_of_stars = total_number_of_stars
while number_of_stars >= 1:
    number_of_spaces = total_number_of_stars - number_of_stars # calculate current layer spaces
    print(" " * int(number_of_spaces / 2) + "*" * number_of_stars + " " * int(number_of_spaces / 2)) # print: space + stars + space
    number_of_stars -= 2 # decrease the number of stars.
```

</details>

In [ ]:
# Put your code here

## Functions 

A function is a block of code that runs when it is called. Functions are created using the "`def`" keyword.

A function is called by using the function name with paranthesis: Information (such as values, lists, tuples, dicts etc.) can be passed to a function as arguments:

We can pass several arguments:

In [ ]:
def my_multiply(a,b):
    print(a*b)

my_multiply(3,5)

We can also assign default values to arguments, so the user doesn't need to provide them if they don't want to. Below, the argument denominator wil be assigned the value 10, unless it is overriden in the function call:

In [ ]:
def divide(numerator, denominator = 10):
    return(numerator/denominator)
    
print(divide(300))
print(divide(300, 5))

# We can also provide arguments to a function using keywords - that way we don't need to have them in the correct order:
print(divide(denominator=5, numerator=300)) # 300/5

## Time to try

### Write a function that find the [hypotenuse](https://en.wikipedia.org/wiki/Pythagorean_theorem) of a right triangle (Hint: use the Pythagorean theorem).



E.g. compute_hypotenuse(3, 4) → output: 5.0

<details>
<summary style="color: yellow; font-weight: bold;">Hint</summary>

```python
def compute_hypotenuse(side1, side2):
    
    # Inputs:
    # side1 - the input argument for one side of the triangle
    # side2 - the input argument for another side of the triangle
    
    # Outputs:
    # hypotenuse - the calculated output from side1 and side2
    
    hypotenuse = (side1**2+side2**2)**0.5
    
    return hypotenuse ## Return the calculation here

a = 3
b = 4
c = compute_hypotenuse(a, b)
print(c)
```

</details>

In [ ]:
# Put your code here

<div class="alert alert-block alert-info">

# 2. NumPy basics

We will be using the NumPy in this workshop! Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. If you are already familiar with MATLAB, you might find this tutorial useful to get started with Numpy.

<img src="https://upload.wikimedia.org/wikipedia/commons/1/1a/NumPy_logo.svg" width="400" align="center">

## Numpy Documentation

The official NumPy [documentation](https://numpy.org/doc/stable/) serves as a comprehensive resource for learning and utilizing the library. It contains detailed explanations of NumPy's functions, methods, and objects, along with examples and usage guidelines. 


## Install NumPy Libaray

If you have already installed Numpy following the Anaconda installation instruction, you can skip this step.

If you haven't, you can install Numpy using `pip` in Jupyter notebook by simply putting a `!` mark before terminal commands.

In [ ]:
!pip install numpy

## Importing NumPy Library

To import the NumPy library (or any library) in Python, you can use the `import` keyword followed by the library name:

In [ ]:
import numpy as np

With this import statement, you can access NumPy functions and objects using the `np` alias. For instance, you can create a NumPy array by calling `np.array()`.

Using the `np` alias is a common practice in the Python community as it reduces the amount of typing required when working with NumPy functions and improves code readability.

Once you have imported NumPy, you can start using its functionality in your Python script or interactive session. Remember to ensure that NumPy is installed in your Python environment before attempting to import it.

## Numpy Arrays and Indexing

A NumPy array is a grid of values, where all the values have the same type and are indexed using nonnegative integers. The array's rank refers to the number of dimensions it has, and its shape is defined by a tuple of integers indicating the size along each dimension.

NumPy arrays can be created by passing nested Python lists as input, and individual elements can be accessed using square brackets.

In [ ]:
a = np.array([1, 2, 3])   # Create a numpy array (rank 1 array) - basically, passing a list into np.array() function
print(type(a))            # Prints the type of the array
print(a.shape)            # Prints the shape of the array
print(a[0], a[1], a[2])   # Prints the 1st, 2nd and 3rd element of the array
a[0] = 5                  # Change the 1st element of the array
print(a)                  # Prints the modified array

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints the shape of the array
print(b[0, 0], b[0, 1], b[1, 0])   # Prints some elements using indexing

Numpy also provides many functions to create arrays/matrices:

In [ ]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((2,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]
                      #          [ 1.  1.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)

## Time to try

Using NumPy to perform the following tasks:

a. Create a NumPy array of size 4x4 filled with random integers between 1 and 10.

b. Print the array.

c. Print the shape of the array.

d. Access and print the element in the second row and third column.

Check out the numpy function `np.random.randint()`. Search it on Google. (your best coding assistant!)

<details>
<summary style="color: yellow; font-weight: bold;">Hint</summary>

Document for `np.random.randint()`:
https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

```python
# Create a 4x4 array filled with random integers between 1 and 10
arr = np.random.randint(1, 11, size=(4, 4))

# Print the array
print("Array:")
print(arr)

# Print the shape of the array
print("Array shape:")
print(arr.shape)

# Access and print the element in the second row and third column
print("Element in the second row and third column:", arr[1, 2])
```

</details>

In [ ]:
# Put your code here

## Array slicing

NumPy provides various methods for indexing arrays.

One of the methods is slicing, which is similar to how Python lists are sliced. Since NumPy arrays can have multiple dimensions, you need to specify a slice for each dimension of the array.

In [ ]:
# Create the following rank 2 array with shape (2, 3)
# [[ 1  2  3 ]
#  [ 4  5  6 ]
#  [ 7  8  9 ]]
a = np.array([[1,2,3], [4,5,6], [7,8,9]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [5 6]]
b = a[:2, 1:3]
print(b)

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 99     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "99"

In addition, it is possible to combine integer indexing with slice indexing. However, this operation will result in an array with a lower rank compared to the original array.

It is worth noting that this behavior differs significantly from how array slicing is handled in MATLAB.

In [ ]:
# Create the following rank 2 array with shape (2, 3)
# [[ 1  2  3 ]
#  [ 4  5  6 ]
#  [ 7  8  9 ]]
a = np.array([[1,2,3], [4,5,6], [7,8,9]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[4 5 6] (3,)"
print(row_r2, row_r2.shape)  # Prints "[[4 5 6]] (1, 3)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2 5 8] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 5]
                             #          [ 8]] (3, 1)"

## Time to try

Using NumPy to perform the following tasks:

a. Create a 4x4 NumPy array filled with integers from 1 to 16.

b. Extract the first row of the array. Then modify the first element in the subarray to 99.

c. Extract the last column of the array. Then modify the second element in the subarray to 88.

d. Extract the 2x2 central array of the array. Then modify the second row second column element of the subarray to 77.

e. Now print the final 4x4 Numpy array.


<details>
<summary style="color: yellow; font-weight: bold;">Hint</summary>

```python
# Create a 4x4 array filled with integers from 1 to 16
array_4x4 = np.arange(1, 17).reshape(4, 4)
print("Original Array:")
print(array_4x4)
print()

# Extract the first row of the array
first_row = array_4x4[0, :]
print("First Row:")
print(first_row)
first_row[0] = 99  # Modify the first element in the subarray
print("Modified First Row:")
print(first_row)
print()

# Extract the last column of the array
last_column = array_4x4[:, -1]
print("Last Column:")
print(last_column)
last_column[1] = 88  # Modify the second element in the subarray
print("Modified Last Column:")
print(last_column)
print()

# Extract the 2x2 central array of the array
central_array = array_4x4[1:3, 1:3]
print("2x2 Central Array:")
print(central_array)
central_array[1, 1] = 77  # Modify the second row second column element of the subarray
print("Modified 2x2 Central Array:")
print(central_array)
print()

# Print the 4x4 NumPy array
print("Final 4x4 NumPy Array:")
print(array_4x4)
```

</details>

In [ ]:
# Put your code here.

## Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)


# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)


# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)


# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)


# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

Numpy provides many useful functions for performing computations on arrays; one of the most useful is sum:

In [ ]:
x = np.array([[1,2],[3,4]])

print(x)
print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object

In [ ]:
x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

The `np.mean()` function calculates the mean (average) of an array.

In [ ]:
x = np.array([1, 2, 3, 4, 5])

mean = np.mean(x)

print(mean)  # Output: 3.0

In this example, the mean of the elements in the array x is calculated and stored in the mean variable.

The `np.max()` function finds the maximum value in an array.

In [ ]:
x = np.array([10, 5, 8, 12, 3])

max_value = np.max(x)

print(max_value)  # Output: 12

In this example, the maximum value in the array x is found and stored in the max_value variable.

These are just a few examples of the many functions available in NumPy. The library offers a wide range of functions for various mathematical operations, array manipulation, statistical calculations, and much more.

Matrix multiplication in Numpy is fairly easy as well.

In [ ]:
# Define matrices A and B
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

# Matrix multiplication using numpy.dot()
result_dot = np.dot(A, B)
# Matrix multiplication using @ operator
result_at_operator = A @ B

print("Result using np.dot():")
print(result_dot)

print("\nResult using @ operator:")
print(result_at_operator)

## Time to try

Using NumPy to perform the following tasks:

a. Create two 2x2 NumPy arrays filled with 1 to 4 and 5 to 8.

b. Compute and print the element-wise sum, difference, product, and division of the arrays.

c. Print the sum of all elements, the maximum and the minimum value in one of the arrays.

d. Print the transpose of one of the arrays.

e. Perform matrix multiplication between the first array and the traspose of the second array, and print the results.

<details>
<summary style="color: yellow; font-weight: bold;">Hint</summary>

```python
# a.
array1 = np.arange(1, 5).reshape(2, 2)
array2 = np.arange(5, 9).reshape(2, 2)
print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)

# b.
print("\nElement-wise Sum:")
print(array1 + array2)

print("\nElement-wise Difference:")
print(array1 - array2)

print("\nElement-wise Product:")
print(array1 * array2)

print("\nElement-wise Division:")
print(array1 / array2)

# c.
print("\nSum of all elements in Array 1:", np.sum(array1))
print("Maximum value in Array 1:", np.max(array1))
print("Minimum value in Array 1:", np.min(array1))

# d.
print("\nTranspose of Array 2:")
print(np.transpose(array2))

# e.
print("\nMatrix Multiplication:")
result = np.dot(array1, np.transpose(array2))
print(result)

```

</details>

In [ ]:
# Put your code here

<div class="alert alert-block alert-info">

# 3. Matplotlib basics <a class="anchor" id="matplotlib"></a>

<img src="https://matplotlib.org/stable/_images/sphx_glr_logos2_003.png" width="400" />

Matplotlib is a popular Python library used for creating visualizations and plots. It provides a wide range of plotting functions and options, allowing users to create line plots, scatter plots, bar plots, histograms, and many other types of charts. Matplotlib provides a flexible and customizable interface, enabling users to fine-tune their plots with various styling options, labels, titles, and annotations. With its intuitive API and extensive documentation, Matplotlib is widely used in data exploration, scientific research, and data visualization tasks in Python.

First, let's install the `matplotlib` library using `pip`

In [ ]:
!pip install matplotlib

Let's import `matplotlib` and called it `plt` for short.

In [ ]:
import matplotlib.pyplot as plt

## Basic plotting
Some basic plotting you can do with matplotlib:
 - Plot y versus x as lines and/or markers with `plot()` function.
 - A scatter plot of y vs. x with varying marker size and/or color with `scatter()` function.

In [ ]:
# Generate some random points
x = [15, 20, 34, 49, 58, 62, 79, 88]
y = [13, 22, 38, 41, 56, 61, 78, 81]

# Plot a line plot using plot()
plt.figure()    # Create a new figure
plt.plot(x, y, color='b', marker = "o") # Plot y against x. Set the color to blue ("b") and use circle markers ("o")
plt.ylabel('Y') # Label the x axis
plt.xlabel('X') # Label the y axis
plt.title("Random points")  # Set a title for the plot

# Scatter the points using scatter()
plt.figure()    # Create a new figure
plt.scatter(x, y, c = "r", marker = "*") # Scatter y against x. Set the color to red ("r") and use star markers ("*")
plt.ylabel('Y') # Label the x axis
plt.xlabel('X') # Label the y axis
plt.title("Random points")  # Set a title for the plot

plt.show()  # Show the plots

You can overlap plots onto each other in the same figure with legends. You can also annotate specific points if you want.

In [ ]:
# Generate some random points
x = [15, 20, 34, 49, 58, 62, 79, 88]
y = [13, 22, 38, 41, 56, 61, 78, 81]
z = [17, 26, 33, 47, 53, 66, 72, 87]

# Plot a line plot using plot()
plt.figure()        # Create a new figure
plt.plot(x, y, color='b', marker = "o") # Plot y against x. Set the color to blue ("b") and use circle markers ("o")
plt.scatter(x, z, c="r", marker = "*") # Scatter z against x on the same figure. Set the color to red ("r") and use star markers ("*")
plt.annotate("Here", xy=(51, 41), color='r') # Annotate at location (51, 41) with red text
plt.ylabel('Y/Z')   # Label the x axis
plt.xlabel('X')     # Label the y axis
plt.legend(['Line plot', 'Scatter plot']) # Add legends
plt.title("Random points")  # Set a title for the plot

plt.show()  # Show the plots

## Time to Try
### Plot the curve of function f(x) = ln(x) / x where x > 0 and x <= 3
__hint__: x = numpy.linspace(start, end, number_of_digits)  # Generate 100 evenly spaced values between start and end

<details>
<summary style="color: yellow; font-weight: bold;">Hint</summary>

```python
import numpy as np
import matplotlib.pyplot as plt

def f(x):
    res = np.log(x) / (x - 1)
    return res

x = np.linspace(0, 3, 100)
y = f(x)

plt.figure()
plt.plot(x, y)
plt.title("line plot of function f(x)")
plt.show()
```

</details>

In [ ]:
# put your code here

### Visualising random walk
A random walk is a person starting from a location and randomly walking. In our settings, let's say the person starts at (0, 0) and each time, the person walks, he/she takes a random action sampled from Normal(0, 1). After 5000 steps, what will the trajectory look like?

<details>
<summary style="color: yellow; font-weight: bold;">Hint</summary>

```python
np.random.seed(1)
x, y = np.random.normal(size=(2, 5000)).cumsum(axis=1)
x = np.insert(x, 0, 0)
y = np.insert(y, 0, 0)

plt.plot(x, y, zorder=1)
plt.scatter(0.0, 0.0, marker="x", s=150, c="darkorange", zorder=2)
plt.show()
```

</details>

In [ ]:
# Put your code here

That is all for this notebook. We hope you enjoyed it and see you in the next one!  